using UnityEngine;

// 4. A침adir Debug.DrawRay(this.transform.position,direction,Color.red) para depuraci칩n para comprobar que la direcci칩n
// est치 correctamente calculada. 

public class Script4 : MonoBehaviour
{
    public Transform goal;
    public float speed = 1.0f;
    
    private Vector3 direction;

    void Start()
    {
        transform.LookAt(goal);
    }
    
    void Update()
    {
        direction = goal.position - transform.position;
        transform.Translate(direction.normalized * (speed * Time.deltaTime), Space.World);
        
        Debug.DrawRay(transform.position, direction, Color.red);
    }
}